version: '3'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  config-server:
    build: config-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8888:8888

  zuul-apigateway:
    build: zuul-apigateway/
    depends_on:
      - config-server
      - eureka-server
      - muzix-service
    restart: always
    network_mode: "host"

    hostname: localhost
    ports:
      - 8080:8080

  muzix-service:
    build: muzixApp-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8011:8011
    depends_on:
      - config-server
      - eureka-server


